### ISSUE TITLE
Add VACF and logarithmic MSD sampling

### ISSUE THREAD

**Issue by toastedcrumpets** [dynamomd/DynamO#30]
For project students working on transport properties (and tutorial 4), add VACF and logarithmic MSD sampling.

**Comment by edwinb-ai** [comment]
Hello @toastedcrumpets I actually would like to know how to do this. You mentioned in the last comment that an external script suffices, but I don't see how this might be done, since the only options for extracting snapshots are `--snapshot` and `--snapshot-events`, and neither would allow to specify the exact time at which to extract the snapshot in a logarithmic scale. Thank you in advance.

**Comment by toastedcrumpets** [comment]
Hi,
You can currently collect the VACF in linear scale as described here:
https://dynamomd.com/index.php/outputplugins.html#vacf
This is powerful for short times as it performs the standard multi-origin averaging in time; however, the cost in memory is O(NxL) where L is the length of the correlator. That means the VACF correlator plugin simulations uses, by default, 50x more memory than not having it enabled (!).

If you want access to long times, I would just drop snapshots to disk in linear time, then go back and take a VACF from those using a script to load each file in whatever combination you want to do (i.e. logarithmically spaced if you want to save on loading images, or just a normal S^2 comparison of all images where S is the number of snapshots).

I have logarithmic sampling for the other transport coefficients as they are only a few bytes per sample so the memory penalty is neglible. With the VACF and MSD you're storing snapshots so you need to use disk most of the time. 

Hope this helps explain the choice.
